### ISSUE TITLE
How to deploy a React application

### ISSUE THREAD

**Issue by ldoguin** [CleverCloud/doc.clever-cloud.com#241]

**Comment by divarvel** [comment]
I'm not sure how to document that

**Comment by BlackYoup** [comment]
Instead of having a page for react only, have a page for front end only applications? (that would work for react, angular, vue, ...). We would only have to say "use the static instance, configure the webroot, configure your package.json and add the build hook"

The static files documentation page is a bit vague regarding how to do all of this, so either we improve it, or we create a new dedicated page.

What do you think @divarvel ?

**Comment by gaelreyrol** [comment]
Closing in favor of: https://github.com/orgs/clever-cloud-examples/projects/1#card-64343260

**Comment by LouisAugry** [comment]
> Closing in favor of: https://github.com/orgs/clever-cloud-examples/projects/1#card-64343260

Link is down

**Comment by gaelreyrol** [comment]
> > Closing in favor of: https://github.com/orgs/clever-cloud-examples/projects/1#card-64343260
> 
> Link is down

https://github.com/orgs/CleverCloud/projects/2#card-65069423

**Comment by MBach** [comment]
So, how do you deploy React App?
